name: Rust CD

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish
      run: cargo publish --token ${{ secrets.CRATES_IO }}
